### ISSUE TITLE
KeyError: login in github_utils adding author

### ISSUE THREAD

**Issue by navignaw** [Skydio/revup#178]
**Describe the bug**
`revup upload` fails with a python KeyError if a reviewer author is missing the "login" attribute.

I am fairly sure this is due to a review from an automated app, i.e.
![Screenshot 2024-05-02 at 8 05 24 AM](https://github.com/Skydio/revup/assets/4044514/5c059c43-ea4c-4880-a756-b85f7377f102)

as it started failing immediately after this reviewer left an automated comment on the PR.

**Expected behavior**
`revup upload` works as intended

**To Reproduce**

1. Create a PR with an automated reviewer. One way to do so is to set up the GHA https://github.com/googleapis/code-suggester, but there are probably easier ways to automate adding a reviewer
2. Run `revup upload` against that topic

**Logs**

```
Traceback (most recent call last):
  File "/usr/local/bin/revup", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/site-packages/revup/__main__.py", line 18, in _main
    sys.exit(asyncio.run(main()))
  File "/usr/local/Cellar/python@3.8/3.8.18/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.8/3.8.18/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/revup/revup.py", line 393, in main
    return await upload.main(
  File "/usr/local/lib/python3.8/site-packages/revup/upload.py", line 48, in main
    await topics.query_github()
  File "/usr/local/lib/python3.8/site-packages/revup/topic_stack.py", line 1015, in query_github
    ) = await github_utils.query_everything(
  File "/usr/local/lib/python3.8/site-packages/revup/github_utils.py", line 276, in query_everything
    reviewers.add(revs["author"]["login"])
KeyError: 'login'
```

**Comment by navignaw** [comment]
It looks like there is a check for login in the `reviewRequests` case. Any objections to just adding the same `if "login" in X` check to all of the other branches?

https://github.com/Skydio/revup/blob/71ca5eb4d8d47536a1c1052e171aaaee8f353632/revup/github_utils.py#L271
